"""Add user_id to feedback

Revision ID: f6beeff25c7d
Revises: 1d20acc41ca7
Create Date: 2025-11-18 01:09:46.969833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6beeff25c7d'
down_revision = '1d20acc41ca7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        # 1.1 Встановлюємо стовпець user_id як NOT NULL
        batch_op.alter_column('user_id',
                       existing_type=sa.INTEGER(),
                       nullable=False)
        # 1.2 Додаємо зовнішній ключ з явним ім'ям 'fk_cart_user_id'
        batch_op.create_foreign_key('fk_cart_user_id', 'users', ['user_id'], ['id'])

    # 2. Зміни для таблиці feedback
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        # 2.1 Додаємо стовпець user_id
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # 2.2 Додаємо зовнішній ключ з явним ім'ям 'fk_feedback_user_id'
        batch_op.create_foreign_key('fk_feedback_user_id', 'users', ['user_id'], ['id'])

    # 3. Зміни для таблиці orders
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # 3.1 Додаємо зовнішній ключ з явним ім'ям 'fk_orders_user_id'
        # (Стовпець user_id вже існував, тому його не додаємо)
        batch_op.create_foreign_key('fk_orders_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
